language: node_js
node_js:
- lts/*
- node
deploy:
  provider: npm
  email: andrew@balmos.org
  api_key:
    secure: KS/Sp8edkmV0ZJFAejz1ImIGrHUfXy1DQWHqFbl6+CUBIqikpNSS9hUlmc8CEE8+e2LczKb3/MJRlVnVcw+VSNblkWWSWQTKppEcOYn3mtw8+cGD33JnReLpLb8oFBzEb6EZABLMF5RNrGvsbhVnzFhzV53q+PzQAozvyPUj4ns=
  on:
    tags: true
    all_branches: true
    repo: OADA/oada-lookup-js
before_install:
- npm install -g gulp
script:
- gulp lint
- gulp style
- npm run cover
after_success:
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls --verbose
